### ISSUE TITLE
Reporting a security issue

### ISSUE THREAD

**Issue by jessysaurusrex** [OmniFlix/omniflixhub#110]
I'm working with the development teams who are building the Interchain Stack, and I am aware of a security vulnerability in your code. I would like to report it so that we can coordinate patching to protect your chain. 

Please reach out to me at security@amulet.dev so that we can coordinate privately. Thanks!

**Comment by Kwaskoff** [comment]
is this your patch?
```
verifying github.com/bianjieai/nft-transfer@v1.1.3-ibc-v7.3.0: checksum mismatch
	downloaded: h1:ItdjA6AUyt3SjiN1HxD0DH3OkyMZBqKSKSQYFDF3Ue8=
	go.sum:     h1:399lErsTpI+faTerw5Q4OuVlXAmAQSuibVvxHR3C6OY=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

```

**Comment by jessysaurusrex** [comment]
Not me! I am trying to get an email security contact for your team for future security coordination efforts.

**Comment by harish551** [comment]
Hi @jessysaurusrex 
here is our security contact: security@omniflix.network
